pawpals/urls.py
from django.conf.urls import url
from pawpals import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # General pages for basic interactions such as browsing to home, about, login and logout
    url(r'^shelters$', views.shelters, name='shelters'),
    url(r'^$', views.home, name='home'),
    url(r'^about', views.about, name='about'),
    url(r'^request/(?P<dog_slug>[\w\-]+)/$', views.request, name='request'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^login/requests/$', views.show_requests, name='requests'),
    url(r'^logout/', auth_views.logout, {'next_page': 'home'}, name='logout'),    #redirects to homepage

    # Pages to delete user accounts and dogs
    url(r'^delete/$', views.deactivate_user, name='deactivate_user'),
    url(r'^delete_dog/(?P<dog_slug>[\w\-]+)/$', views.remove_dog, name='remove_dog'),

    # pages related to reviews (adding and deleting reviews)
    url(r'^add-review/(?P<request_pk>[\w\-]+)$', views.add_review, name="add_review"),
    url(r'^edit-review/(?P<request_pk>[\w\-]+)$', views.edit_review, name="edit_review"),

    # Account registration and management pages
    url(r'^register/$',views.register,name='register'),
    url(r'^professional/$',views.professional,name='professional'),
    url(r'^personal/$',views.personal,name='personal'),
    url(r'^edit/$', views.edit, name='edit'),

    # Main entity pages (dogs and shelter displays)
    url(r'^shelters/(?P<shelter_slug>[\w\-]+)/$', views.show_shelter, name='show_shelter'),
    url(r'^dogs/(?P<dog_slug>[\w\-]+)/$', views.show_dog, name='show_dog'),
    url(r'^dogs/$',views.dog_search, name='dogs'),

    # AJAX version of reviews and dogs pages
    url(r'^ajax/show_reviews/', views.show_reviews, name = "show_reviews"),
    url(r'^ajax/get_dogs/', views.get_dogs, name = "get_dogs"),


]

pawpals_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from pawpals import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^pawpals/', include('pawpals.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pawpals/models.py
import os

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.fields.related import ManyToManyField, OneToOneField
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.template.defaultfilters import slugify, default
from django.utils import timezone
from django.db.models import Q
from django.shortcuts import redirect

import numpy as np


# default values
phone_len = 20
standard_char_len = 200
extended_char_len = 500
difficulty_validators = [MinValueValidator(0), MaxValueValidator(5)]

class User(AbstractUser):
    # default fields: username, first_name, last_name, email, password, groups, 
    #                 user_permissions, is_staff, is_active, is_superuser, last_login, date_joined
    
    is_manager = models.BooleanField("manager status", default=False)
    is_standard = models.BooleanField("standard user status", default=False)

class UserProfile(models.Model):
    
    # relationship fields
    user = models.OneToOneField(User, primary_key = True, on_delete=models.CASCADE)

    # fields
    def user_image_path(self, filename):
        return (os.path.join("user_profile_images", filename))
    
    profile_picture = models.ImageField(upload_to=user_image_path, blank= True)
    phone_contact = models.CharField(max_length = phone_len, unique = True, blank = "True", null = True)

    def __str__(self):
        return self.user.username

class Shelter(models.Model):
    
    # relationship fields
    manager = OneToOneField(User, blank = True, on_delete=models.CASCADE)

    # fields
    name = models.CharField(max_length = 128, primary_key = True) # name and surname
    bio = models.CharField(max_length = extended_char_len)
    webpage = models.URLField(blank = "True")
    phone_contact = models.CharField(max_length = phone_len, unique = True)
    availability_info = models.CharField(max_length = extended_char_len)
    location = models.CharField(max_length = standard_char_len)
    avg_difficulty_rating = models.IntegerField(default = 5, validators = difficulty_validators)

    slug = models.SlugField(unique = True)

    def shelter_image_path(self, filename):
        return (os.path.join("shelters_profile_images", filename))

    profile_picture = models.ImageField(upload_to=shelter_image_path, blank="True")


    def save(self, *args, **kwargs):

        # set slug
        self.slug = slugify(self.name)

        # set average difficulty rating
        sum = 0
        count = 0

        shelter_dogs = Dog.objects.all().filter(dog_shelter = self)

        for dog in shelter_dogs:
            reviews = Review.objects.all().filter(reviewed_dog = dog)
            sum += np.sum([review.difficulty_rating for review in reviews])
            count += len(reviews)

        if (count):
            self.avg_difficulty_rating = int(sum/count)
        else:
            self.avg_difficulty_rating = 0


        super(Shelter, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Dog(models.Model):
    # relationship fields
    dog_shelter = models.ForeignKey(Shelter, blank = True, on_delete=models.CASCADE)

    # ID (or pk) is implicitly made by Django
    # id = models.AutoField(primary_key=True)

    # fields
    name = models.CharField(max_length = standard_char_len)
    bio = models.CharField(max_length = extended_char_len)
    breed = models.CharField(max_length = standard_char_len)
    difficulty = models.IntegerField(default = 0, validators = difficulty_validators)
    size = models.CharField(max_length = 1, choices = (("S", "Small"),
                                                       ("M", "Medium"),
                                                       ("L", "Large")))
    gender = models.CharField(max_length = 1, choices = (("M", "Male"),
                                                         ("F", "Female")))
    is_puppy = models.BooleanField(default = "False")
    is_childfriendly = models.BooleanField(default = "False")
    slug = models.SlugField(unique = True)
    completed_request_count = models.IntegerField(default=0)

    def dog_image_path(self, filename):
        return (os.path.join("dogs_profile_images", filename))

    profile_picture = models.ImageField(upload_to=dog_image_path, blank="True")


    def save(self, *args, **kwargs):

        # set average difficulty rating
        reviews = Review.objects.all().filter(reviewed_dog = self)

        if reviews:
            avg_difficulty = 0

            for review in reviews:
                avg_difficulty += review.difficulty_rating

            avg_difficulty = avg_difficulty/len(reviews)
        else:
            avg_difficulty = 3;

        self.difficulty = avg_difficulty

        # set number of completed (or reviewed) requests
        self.completed_request_count = Request.objects.all().filter(Q(requested_dog=self) & (Q(status="C") | Q(status="R"))).count()

        # if called upon object creation, save first, so pk is created and slug in not None
        if not(self.pk):
            super().save(*args, **kwargs)
        else:
            self.slug = slugify(self.name + "-" + str(self.pk))
            super(Dog,self).save(*args, **kwargs)

    def __str__(self):
        return self.name

# Sets up slug upon creation
@receiver(post_save, sender = Dog)
def update_slug(sender, instance, created, *args, **kwargs):
    if created:
        instance.slug = slugify(instance.name + "-" + str(instance.pk))
        instance.save()

class Request(models.Model):
    # relationship fields
    requesting_user = models.ForeignKey(User, related_name="requesting_user", on_delete=models.CASCADE)
    request_manager = models.ForeignKey(User, related_name="request_manager", blank = True, on_delete=models.CASCADE)
    requested_dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    
    # fields
    date = models.DateTimeField(default = timezone.now())
    status = models.CharField(max_length = 1, choices = (("A", "Accepted"),
                                                          ("D", "Denied"),
                                                          ("P", "Pending"),
                                                          ("C", "Completed"),
                                                          ("R", "Reviewed")))
    message = models.CharField(max_length = extended_char_len, blank = True)

    def save(self, *args, **kwargs):
        
        # set status to reviewed if request has review
        if (Review.objects.all().filter(request = self)) and not(self.status.__eq__("R")):
            self.status = "R"

        super(Request, self).save(*args, **kwargs)
        
        # save dog to update request count 
        self.requested_dog.save()

    def __str__(self):
       dog_name = str(self.requested_dog)
       user_name = str(self.requesting_user)
       manger_name = str(self.request_manager)
       return (dog_name  + " - by " + user_name + " (" + self.date.strftime("%B %d, %Y") + ")")

class Review(models.Model):
    # relationship fields
    request = models.OneToOneField(Request, on_delete=models.CASCADE)
    reviewing_user = models.ForeignKey(User, on_delete=models.CASCADE)
    reviewed_dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    
    # fields
    difficulty_rating = models.IntegerField(default = 3, validators = difficulty_validators, blank=True)
    comment = models.CharField(max_length = extended_char_len)
    date = models.DateTimeField(default = timezone.now())

    def save(self, *args, **kwargs):

        # set user and dog
        self.reviewing_user = self.request.requesting_user
        self.reviewed_dog = self.request.requested_dog

        # update dog upon creating/changing review
        super(Review, self).save(*args, **kwargs)

        # change request to "Reviewed"
        self.request.status = "R"
        self.request.save()

        # save dog and shelter to update average difficulty reviews
        self.reviewed_dog.save()
        self.reviewed_dog.dog_shelter.save()

    def __str__(self):
        dog_name = str(self.reviewed_dog)
        user_name = str(self.reviewing_user)

        return (dog_name  + " (" + self.date.strftime("%B %d, %Y") + ")")

pawpals/forms.py
from django import forms
from django.contrib.auth.models import User
from pawpals.models import *

# Using Django's base User model
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_picture','phone_contact')

# All forms from here inherit the fields from the model specified in class Meta.
class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('difficulty_rating', 'comment')


class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ('message',)

class RequestStatusForm(forms.ModelForm):

    previous_status = forms.CharField(widget=forms.HiddenInput)
    CHOICES =  (("", "-----"),
                ("A", "Accepted"),
                ("D", "Denied"),
                ("C", "Completed"))

    status = forms.ChoiceField(choices = CHOICES)

    class Meta:
        model = Request
        fields = ('status',)

    def clean(self):
        cleaned_data = super().clean()
        c_status = cleaned_data.get("status")
        p_status= cleaned_data.get("previous_status")
        
        # pending to accepted
        p_a = (p_status == "P") and (c_status == "A")
        # pending to denied
        p_d = (p_status == "P") and (c_status == "D")
        # accept to completed
        a_c = (p_status == "A") and (c_status == "C")

        if not(p_a) and not(p_d) and not(a_c):
            raise forms.ValidationError("Cannot change status backward.")

class UserEditingForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_picture', 'phone_contact')

class UserCoreEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)


class ShelterEditingForm(forms.ModelForm):
    class Meta:
        model = Shelter
        fields = ('name', 'bio', 'webpage',
                  'phone_contact',
                  'availability_info',
                  'location')

class DogEditingForm(forms.ModelForm):

    class Meta:
        model = Dog
        fields = ('name', 'bio', 'breed', 'size',
                   'gender', 'is_puppy',
                   'is_childfriendly',
                   'profile_picture')

templates/pawpals/about.html
{% extends 'pawpals/base.html' %}

{% block title_block %}
    FAQ and About
{% endblock %}

{% block body_block %}
<!-- Basic Grid Layout with a manifesto as the 'about' section -->
  <div class="container">

    <div class="row">
      <div class="col-md-7">
        <h4 class="featurette-heading">About Us
        </h4>
        <p class="lead">"Dogs have a way of finding the people who need them,
            and filling an emptiness we didn't ever know we had." - Thom Jones <br/><br/>
            Even as students hailing from four completely separate corners of the globe, we understand the important
            role that the domesticated animal can play in a persons life. So much so that we
            decided to create an app that would aid pet-seekers in their quest for their purrfect companion, working to
            pair owners with their dream pet whilst offering those in need (both human and otherwise) much needed
            affection and time for bonding in a safe, comfortable environment.<br/><br/>
        Sara Jakubiak<br/>
        Serhat Degirmenci<br/>
        Bita Fardoo<br/>
        Ibai Castells</p>

      </div>
    </div>
<div>
    <!-- divider used to signify the FAQ section is next, basic collapse buttons used to display question answers only
    when needed -->
    <hr class="featurette-divider">
<h1 class="featurette-heading">Frequently Asked Questions
        </h1>
        <button class="btn btn-outline-info" data-toggle="collapse" data-target="#q1">What Is PawPals?</button>
    <div id="q1" class="collapse">
    <div class="row">
    <div class="col-md-7">
        <p class="lead">At PawPals we work to match those who want a dog but don't have the time or money to take
            care of one.
        We work alongside dog shelters so that dogs who need love and attention can go on walks and spend quality
            time with amazing people like you!
          So what are you waiting for, find yourself a PawPal and go make some memories! </p>

      </div>
    </div>
    </div>
            <button class="btn btn-outline-info" data-toggle="collapse" data-target="#q2">How Can I Register?</button>
    <div id="q2" class="collapse">
    <div class="row">
    <div class="col-md-7">
        <p class="lead">If you look to the top right you will be able to click on the 'Sign Up' button (it's
            highlighted
        in blue!), just fill out the form and click the Register button and you're all set!</p>

      </div>
    </div>
    </div>
            <button class="btn btn-outline-info" data-toggle="collapse" data-target="#q3">Can I Delete My Account?</button>
    <div id="q3" class="collapse">
    <div class="row">
    <div class="col-md-7">
        <p class="lead">"If you feel your time at PawPals is at an end you are very welcome to delete your account
        (though we will be sad to see you leave!). If you navigate to the edit profile page (by clicking on the
            'Edit Profile' button at the top right of any page)
        you have the option to delete your account.
        Friendly warning for Shelter Managers: deleting the account of your shelter will subsequently remove all
            PawPals from your shelter from our databases!"</p>

      </div>
    </div>
    </div>
            <button class="btn btn-outline-info" data-toggle="collapse" data-target="#q4">How Can I Request A Dog?</button>
    <div id="q4" class="collapse">
    <div class="row">
    <div class="col-md-7">
        <p class="lead">If you find yourself a PawPal you want to walk; either by the 'Dog's That Need Love'
            section on the homepage
        or through either the Dog Search or Shelter pages, you can click the 'Request a Walk' button below the
            PawPal's image. Just leave a message for the shelter
        outlining your request and submit! The shelter will get back in touch with you about the walk at their
            earliest convinience! </p>
      </div>
    </div>
    </div>
                <button class="btn btn-outline-info" data-toggle="collapse" data-target="#q5">How Can I View/Manage My Requests?</button>
    <div id="q5" class="collapse">
    <div class="row">
    <div class="col-md-7">
        <p class="lead">To View/Manage your requests you first need to navigate to the 'Manage Requests' page,
            which you'll see
        at the top right of any page when you are logged in. For standard users you will be able to view the
            status of every request you've made and easily be able to leave
        a review if you've completed a walk with a certain PawPal from this page. For shelter manager users you
            will be able to view requests made for PawPals your shelter
        houses, and review them as you please - accepting or denying requests based on your availability.</p>
      </div>
    </div>
    </div>
</div>
  </div>
{% endblock %}

templates/pawpals/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8">
        <!-- allows for responsive scaling -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{%  static 'brand.png' %}"/>
<!-- Bootstrap CDN integration -->
       <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

{% block javascript_block %}
{% endblock %}

{% block stylesheet_block %}
        <link rel="stylesheet" type="text/css" href="{% static "styles/base_style.css" %}">
{% endblock %}
<!-- Standard navbar that will be used across all templates -->
<nav class="navbar navbar-expand-sm fixed-top bg-dark" id="navbar">
    <a class="navbar-brand text-white" href="{% url 'home' %}"><img src="{% static "/brand.png" %}" width="30"
      height="30">PawPals</a>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'dogs' %}">Dog Search</a>
      </li>
     <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'shelters' %}">Shelters</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'about' %}">About & FAQ</a>
      </li>

    </ul>

	  <form>
      <ul class="navbar-nav ml-auto">
          <!-- checking whether a user is logged in and showing them certain buttons depending on that -->
          {% if user.is_authenticated %}
          <a class="btn btn-outline-danger text-white" href="{% url 'logout' %}" role="button">Sign Out</a>
          <a class="btn btn-outline-primary text-white" href="{% url 'edit' %}" role="button">Edit Profile</a>
          <a class="btn btn-outline-info text-white" href="{% url 'requests' %}" role="button">Manage Requests</a>
          {% else %}
    <a class="btn btn-outline-success text-white" href="{% url 'login' %}" role="button">Sign In</a>
    <a class="btn btn-outline-info text-white" href="{% url 'register' %}" role="button">Sign Up</a>
          {% endif %}
      </ul>
		  </form>

</nav>
    </head>

        <title>
          {% block title_block %}
          {% endblock %}
        </title>

    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <!-- Using a second navbar in the footer to provide a 'back to top' functionality given that we have some
                big templates -->

        </body>
</html>

templates/pawpals/dog.html
{% extends 'pawpals/base.html' %}
{% load staticfiles %}

{% block javascript_block %}
	<script type="text/javascript" src="{% static 'js/pawpals-ajax.js' %}"></script>
{% endblock %}

{% block stylesheet_block %}
	<link rel="stylesheet" type="text/css" href="{% static "styles/dog.css" %}">
{% endblock %}

{% block title_block %}
	{{ dog.name }}
{% endblock %}



{% block body_block %}
    <!-- displays the profile picture in the database for the dog, if there isn't one, provides a default image -->
          {% if dog.profile_picture %}
        <img class="rectangle" src="{{ MEDIA_URL }}{{ dog.profile_picture }}" alt="Image of Dog" width="400" height="400">
          			{% else %}
          <img class="rectangle center-cropped" src="{% static "default_dog.png" %}" alt="Image of Dog" width="400" height="400">
			{% endif %}
<div>
        <h3> {{dog.name}}</h3>
    <!-- allows a standard user that is logged in to request a walk -->
		  {% if user.is_authenticated %}
            {% if user.is_standard %}

				<a id = "request_button" class="btn btn-success" href="{% url 'request' dog.slug %}"
                   role="button">Request a Walk</a>
</div>

			{% endif %}
          {% endif %}

<!-- Displays the information of the dog in a nice pattern -->

    <div class="row" >

    <div class="col-sm-2">

        <h4>Bio</h4>
		<article>{{ dog.bio }}</article>

     </div>
    <div class="col-sm-2">

        <h4>Breed</h4>
		<p>{{ dog.breed }}</p>

      </div>
    </div>
<div class="row">
    <div class="col-sm-3">

        <h4>Size</h4>
		<p>{{ dog.get_size_display }}</p>

      </div>

    <div class="col-sm-3">

        <h4>Gender</h4>
		<p>{{ dog.get_gender_display }}</p>

      </div>

    <div class="col-sm-3">

        <h4>Puppy?</h4>
		<p>{% if dog.is_puppy %}
						Yes
					{% else %}
						No
{% endif %}</p>
    </div>
</div>
<div class="row">
        <div class="col-sm-2">

        <h4>Child Friendly?</h4>
			<p>{% if dog.is_childfriendly %}
						Yes
					{% else %}
						No
{% endif %}</p>

      </div>
        <div class="col-sm-2">

        <h4>Overall Difficulty</h4>
			<p>{{ dog.difficulty }}/5</p>

      </div>

</div>

<!-- Using AJAX, this button displays the reviews left on this specific dog -->
<div>
{% if user.is_authenticated %}
			{% if user.is_manager %}
					{% if show_delete %}

			<a class="btn btn-outline-danger" href="{% url 'remove_dog' dog.slug %}" >Delete Dog</a>

{% endif %}
			{% endif %}
					{% endif %}

</div>
<button class="btn btn-outline-info" onclick="get_reviews('{% url 'show_reviews' %}', '{{ dog.slug }}', '{% static 'default_user.png' %}' )" data-toggle="collapse"  data-target="#reviewsButton">See Reviews&raquo;</button>

          <div id = "reviewsButton" class="collapse">

              <div>


              <div id="review_block"></div>

          </div>
          </div>
{% endblock %}

templates/pawpals/dogSearch.html
{% extends 'pawpals/base.html' %}
{% load staticfiles %} 


{% block title_block %}
    Find a suitable dog!
{% endblock %}

{% block body_block %}
<div class="fluid-container">

<h1 class="featurette-heading">Find Your Perfect PawPal!</h1>
    <div class="container">
    <hr class="featurette-divider">
    </div>
    <!-- provides functionality to filter through every dog in the database based on the given criteria to then present
    the matching dogs -->
    <button class="btn btn-outline-info" data-toggle="collapse" data-target="#search">Search For A Specific PawPal</button>
	<div id="search" class="collapse">
		<form method="get">
            <div id="dogsearch" class="container">
			{{ filter.form.as_table }}
			<button class="btn btn-outline-success" type="submit">Search</button>
            </div>
		</form>
	</div>

    <div class="row">
            <!-- Uses information passed in the model to create a nice grid layout of all the dogs which can be filtered
             using the 'search' button -->
        {% for dog in filter.qs %}
      <div class="col-lg-3 col-sm-3">
      
      					{% if dog.profile_picture %}
							<img class="rectangle center-cropped" src="{{ MEDIA_URL }}{{ dog.profile_picture }}"
							          alt="Image of Dog" width="200" height="200">
          				{% else %}
							<img class="rectangle center-cropped" src="{% static "default_dog.png" %}" alt="Image of Dog"
                                width="200" height="200">
						{% endif %}
      
        
        <h3>{{ dog.name }}</h3>

          <a class="btn btn-outline-dark" href="{% url 'show_dog' dog.slug %}" role="button">View dog &raquo;</a>
            </p>
      </div>
        {% endfor %}
  </div>
</div>

</div>
{% endblock %}

templates/pawpals/personal.html
{% extends 'pawpals/base.html' %}
{% load staticfiles %}

{% block body_block %}

<h1 class="featurette-heading">Please Fill In Your Details to Register a Personal Account</h1>
    <form id="user_form" method="post" action="{% url 'personal' %}"
              enctype="multipart/form-data">
    <div class="row">
    <div class="col-md-7">

    <!-- standard user form -->
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    </div>
    </div>
    <button type="submit" class="btn btn-outline-success">Submit</button>
    </form>
{% endblock %}

templates/pawpals/requests.html
{% extends 'pawpals/base.html' %}
{% load staticfiles %} 

{% block title_block %}
    Manage your requests
{% endblock %}

{% block body_block %}
<h1 class="featurette-heading">Requests Page</h1>
<ul class="errorlist nonfield"><li>Cannot change status backward.</li></ul>
<!-- A table is used to display the requests in a neat and orderly way -->
	<table id="table">
	
		<tr>
			<!-- table headings -->
			<th>Requested Dog</th>
			
			{% if user.is_standard %}
				<th>Shelter</th>
			{% endif %}
			
			{% if user.is_manager %}
				<th>Person Requesting</th>
				<th>Phone Contact</th>
			{% endif %}
			
			<th>Message</th>
			<th>Date</th>
			<th>Status</th>
			{% if user.is_standard %}
				<th>Review</th>
			{% endif %}
			
			{% if user.is_manager %}
				<th>Change status</th>
			{% endif %}
			
		</tr>	
			
		{% for request, shelter, user_data in requests %}
		<!-- data entries in the table -->
			<div class = "request">
				<tr>
					<td>
						<a href="{% url 'show_dog' request.requested_dog.slug %}">
							{{ request.requested_dog }}
						</a>
					</td>
					
					{% if user.is_standard %}
						<td><a href="{% url 'show_shelter' shelter.slug %}">
						{{ shelter.name }}</a></td>
					{% endif %}
					
					{% if user.is_manager %}
						<td>{{ user_data.username }}</td>
						<td>{{ user_data.phone_contact }}</td>
					{% endif %}
					
						<td>{{ request.message }}</td>
						<td>{{ request.date }}</td>
						<td>{{ request.get_status_display }}</td>
					<!-- if the user is logged in and is a standard user... -->
					{% if user.is_standard %}
					<!-- Check what status this request is at, and depending on the status of the request, either write
					a review update your review or if the status isn't at a point which allows you to do either of
					those things, disable the review button -->
						{% if request.status == "C" %}						

							<td>

								<a class="btn btn-success" href="{% url 'add_review' request.pk %}" role="button">Review walk</a>
							</td>
						{% elif request.status == "R" %}
							<td>
								<a class="btn btn-info" href="{% url 'edit_review' request.pk %}" role="button">Update review</a>

							</td>
						{% else %}
							<td>
								<a class="btn btn-secondary disabled" href="{% url 'edit_review' request.pk %}" role="button" aria-disabled="true">Write Review</a>
							</td>
							
						{% endif %}
					{% endif %}
					<!-- if the logged in user is a manager then allow them to change the status of a request -->
						{% if user.is_manager %}

							<form id="status_update" method="post" action="">
								{% csrf_token %}


								<td><select name="status" required id="id_status">
  <option value="" selected>-----</option>

  <option value="A">Accepted</option>

  <option value="D">Denied</option>

  <option value="C">Completed</option>

</select></td>
				        		<input type='hidden' value='{{ request.pk }}' name='request_object'>
				        		<input type='hidden' value='{{ request.status }}' name='previous_status' >
								<td><button class="btn btn-outline-primary" id="requests_submit" type="submit" name="submit">Change</button></td>
				        	</form>
			        	
						{% endif %}

						
				</tr>
			</div>
			
		{% endfor %}
	</table>

{% endblock %}